### ISSUE TITLE
Admincommands gehen nicht

### ISSUE THREAD

**Issue by 18Karat** [Zmileey/Reallife-V#4]
Keine Errors oder so passiert einfach nichts, habe rank 3 in der datenbank

**Comment by 18Karat** [comment]
Sehe grade das keine Commands funktionieren

**Comment by Zmileey** [comment]
Sie sollten funktionieren!

Sind alle Befehle folgenderweise getestet wurden (z.B. /kick)? denn dies liegt sicherlich nicht an dem Script da es bisher bei jedem funktioniert hat.

**Comment by 18Karat** [comment]
Ja habe alle durch getestet, muss ich irgendwas bei der installation beachten was das auslösen könnte?
